version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: SchoolDatabase
      POSTGRES_PASS: 1234
    volumes:
      - pgdata:/var/lib/posgresql/data
  backapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backapp:/backapp
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: