# Generated by Django 3.2.8 on 2021-11-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdetail',
            name='rollnbr',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
