# Generated by Django 3.2 on 2021-08-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_studentsdetail_student_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdetail',
            name='student_pic',
            field=models.ImageField(default=0, null=True, upload_to='studentpic'),
        ),
    ]
