# Generated by Django 3.2 on 2021-08-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_studentsdetail_student_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdetail',
            name='bloodgroup',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsdetail',
            name='student_pic',
            field=models.ImageField(blank=True, default=0, upload_to='studentpic'),
            preserve_default=False,
        ),
    ]
