# Generated by Django 3.2.8 on 2021-11-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20211130_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='fail',
            field=models.BooleanField(default=False),
        ),
    ]
