# Generated by Django 3.2 on 2021-08-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210826_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetail',
            name='bloodgroup',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='teacher_pic',
            field=models.ImageField(blank=True, upload_to='teacherpic'),
        ),
    ]
