# Generated by Django 3.2.8 on 2021-10-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210826_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=40)),
                ('book', models.FileField(upload_to='books')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolclasses')),
            ],
        ),
    ]
