# Generated by Django 3.2.8 on 2021-10-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20211030_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
