# Generated by Django 3.2.8 on 2021-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_books_bookname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetail',
            name='bloodgroup',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
