# Generated by Django 3.2.8 on 2021-11-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_teacherdetail_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdetail',
            name='currentStandard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='school.schoolclasses'),
            preserve_default=False,
        ),
    ]
