# Generated by Django 3.2.8 on 2021-11-28 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_studentsdetail_currentstandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll_student',
            name='date_enrollinstandard',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
